### ISSUE TITLE
TODO: Blocks generated by FieldVarInput should reflect the correct type

### ISSUE THREAD

**Issue by stefaj** [stefan-j/blockly#11]
Blocks dragged out of FieldVarInput should have the type which they actually reflect. 
This is done by adding the correct TypeExpr to the constructor of FieldVarInput.

Instances:
- [x] Case statement - Should be unpacked and gotten from the constructor
- [x] Functions - All x's should reflect the same type. Stored in argTypes
- [x] Lists - Stored in typeParams
- [x] List comprehensions - Stored in typeParams
